# Generated by Django 4.1.7 on 2023-02-24 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('meta_title', models.TextField()),
                ('meta_description', models.TextField()),
                ('what_is', models.TextField()),
                ('key_things_to_consider', models.TextField()),
                ('faq', models.TextField()),
                ('features', models.TextField()),
                ('prices_of_similar_products', models.TextField()),
                ('content', models.TextField()),
                ('image_url', models.URLField(default='https://robohash.org/test.png')),
                ('abunda_slug', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
