# Generated by Django 4.1.7 on 2023-03-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abunda_url',
            field=models.URLField(default='https://www.shopabunda.com/blog/'),
        ),
    ]
