# Generated by Django 4.1.7 on 2023-03-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_abunda_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='faq',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='key_things_to_consider',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='prices_of_similar_products',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='what_is',
            field=models.TextField(blank=True),
        ),
    ]
