# Generated by Django 4.1.7 on 2023-03-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_summary_alter_article_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abunda_scorecard',
            field=models.TextField(blank=True),
        ),
    ]
